version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.Dockerfile
        ports:
            - "8080:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/laravel-docker
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.Dockerfile
        volumes:
            -   ./:/var/www/laravel-docker
        links:
            - pgsql
    pgsql:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
